baseurl = "https://roboswift.io/"
languageCode = "en-us"
title = "Roboswift"
theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Add your tracking code to enable Google Analytics
googleAnalytics = "UA-89025121-1"
# Posts per page
paginate = 10

[params]
	author = "Miguel Angel Quinones"
	description = "Exploring Swift through projects with automation, robotics, DIY and electronics"
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = ""
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "/img/avatar.png"
	# or use Gravatar by adding your email address to generate a unique avatar
	# gravatar = "miguel@miqu.me"
	headerText = "Swift love through DIY projects"

	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = ""
	copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"


	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = false
		email = "hello@roboswift.io"
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "Roboswift"
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = "miguelquinon"
		wordpress = ""
		youtube = ""
